// Do not edit this file!
// This file may only be edited by Engima's ASCOM Editor!
//
// <ASCOM version="1">
// <Prefix>dre_</Prefix>
// <Functions>
// <Function Name="OnSatchelPlaced" Params="satchel, satchelPos" Ret="false" A="false" C="false" S="true" O="false" OC="false" P="false" />
// </Functions>
// </ASCOM>

ASCOM_ClientID = 0;
ASCOM_CallID = 0;
ASCOM_LastCallID = 0;
ASCOM_LockCallID = 0;

"dre_OnSatchelPlacedEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call dre_OnSatchelPlaced;
        };

        if (_this select 0 == "S" && isServer) then {
            (_this select 1) call dre_OnSatchelPlaced;
        };
    };
};

dre_OnSatchelPlacedServer = {
    if (isNil "_this") then { _this = []; };
    if (isServer) then {
        _this call dre_OnSatchelPlaced;
    }
    else {
        dre_OnSatchelPlacedEventArgs = ["S", _this];
        publicVariable "dre_OnSatchelPlacedEventArgs";
        dre_OnSatchelPlacedEventArgs = [];
    };
};



if (isServer) then {
    "ASCOM_AskForClientID" addPublicVariableEventHandler {
        private ["_unit"];

        _unit = _this select 1;
        ASCOM_AskForClientID = [];
        ASCOM_LastCallID = ASCOM_LastCallID + 1;
        ASCOM_ClientIDResponse = [_unit, ASCOM_LastCallID];
        publicVariable "ASCOM_ClientIDResponse";
    };

    ASCOM_ServerInitialized = true;
    publicVariable "ASCOM_ServerInitialized";
    ASCOM_Initialized = true;
}
else {
    "ASCOM_ClientIDResponse" addPublicVariableEventHandler {
        private ["_array"];

        _array = _this select 1;
        ASCOM_ClientIDResponse = [];

        if (player == (_array select 0)) then {
            ASCOM_ClientID = _array select 1;
            ASCOM_Initialized = true;
        };
    };

    waitUntil {!isNull player};
    ASCOM_AskForClientID = player;
    publicVariable "ASCOM_AskForClientID";
};
